# exp setting
exp_name: 'test' # name that will be used in wandb
ckpt_path: null # checkpoint path, used for evaluation
seed: 42 # random seed
debug: True # debug mode, will use cpu only
devices: [ 0 ] # gpu ids
past_len: 21 # past length  
future_len: 60 #future trajectory


# data related
load_num_workers: 0 # number of workers for loading data
train_data_path: "data" # data path
val_data_path: [ "data_samples/nuscenes" ] # list of paths to the validation data
num_samples: 1 #set to None if you want to use all the data
trajectory_sample_interval: 1 # sample interval for the trajectory
object_type: [ 'VEHICLE' ] #object types included in the training set
