# exp setting
exp_name: 'test' # name that will be used in wandb
ckpt_path: null # checkpoint path, used for evaluation
seed: 42 # random seed
debug: True # debug mode, will use cpu only
devices: [ 0 ] # gpu ids
past_len: 21 # past length  
future_len: 60 #future trajectory


# data related
load_num_workers: 0 # number of workers for loading data
train_data_path: "data" # data path
val_data_path: "data/val"  # list of paths to the validation data
num_samples: 50 #set to None if you want to use all the data
trajectory_sample_interval: 1 # sample interval for the trajectory
object_type: [ 'VEHICLE' ] #object types included in the training set
max_num_agents: 2


# model
use_map_image: False
use_map_lanes: True
num_modes: 6
num_agent_feature: 36
num_map_feature: 29
hidden_size: 256
num_encoder_layers: 2
num_decoder_layers: 8
tx_hidden_size: 1024
tx_num_heads: 4
dropout: 0.1
entropy_weight: 40.0
kl_weight: 20.0
use_FDEADE_aux_loss: True
num_queries_dec: 64
num_queries_enc: 192

# train
max_epochs: 150 #150 #40
learning_rate: 0.0001 # 0.00075 # 1e-3 for lanegcn
learning_rate_sched: [ 10, 20, 30, 40, 50 ]
optimizer: AdamW #According to PyTorch naming
scheduler: multistep # plateau, multistep
ewc_lambda: 2000
grad_clip_norm: 5
train_batch_size: 128 #32 #128
eval_batch_size: 512 #32 #128

# data related
max_num_agents: 32
map_range: 100
max_num_roads: 384
max_points_per_lane: 30 # will be overwritten if manually_split_lane is True
manually_split_lane: False
# lane split related params
point_sampled_interval: 1
num_points_each_polyline: 20
vector_break_dist_thresh: 1.0
