# Configurations for battlespace environment
battlespace_environment:
  bounds:
    x: [-3000, 3000]
    y: [-3000, 3000]
    z: [-100, 100]

  spawning:
    distance_from_other_agents:
      min: 100
      max: 300
    target:
      randomize: false
      position:
        x: 200
        y: 200
        z: 50
      spawn_radius_from_agent:
        min: 300
        max: 500

  # Used to define resolution of sim 
  simulation:
    dt: 0.05 
    frequency: 100  # Hz
    end_time: 50.0 # end time for each episode
  
  agents:
    num_evaders: 1
    num_pursuers: 1
    use_pursuer_heuristics: false
    ai_pursuers: true    

    interaction:
      bubble_radius: 5 # wing span of aircraft
      capture_radius: 50.0 # capture target radius

    relative_state_observations:
      position:
        x:
          low: -750.0
          high: 750.0
        y:
          low: -750.0
          high: 750.0
        z:
          low: -50.0
          high: 50.0

      velocity:
        low: -75.0
        high: 75.0

      attitude:
        low: 0.0
        high: 3.14159

    evaders:
      # observation 
      is_controlled: true
      state_limits:
        x:
          min: -inf
          max: inf
        y:
          min: -inf
          max: inf
        z:
          min: 30.0
          max: 100.0
        phi:
          min: !!float -0.7853981633974483   # -np.deg2rad(45)
          max: !!float 0.7853981633974483    # np.deg2rad(45)
        theta:
          min: !!float -0.4363323129985824   # -np.deg2rad(25)
          max: !!float 0.3490658503988659    # np.deg2rad(20)
        psi:
          min: !!float -3.14159   # -np.deg2rad(360)
          max: !!float 3.14159     # np.deg2rad(360)
        v:
          min: 12.0
          max: 35.0
        vx:
          min: -35.0
          max: 35.0
        vy:
          min: -35.0
          max: 35.0
        vz:
          min: -35.0
          max: 35.0

      control_limits:
        u_phi:
          min: !!float -0.7853981633974483   # -np.deg2rad(45)
          max: !!float 0.7853981633974483    # np.deg2rad(45)
        u_theta:
          min: !!float -0.4363323129985824   # -np.deg2rad(25)
          max: !!float 0.3490658503988659    # np.deg2rad(20)
        u_psi:
          min: !!float -3.14159 #radians
          max: !!float 3.14159  #radians
        v_cmd:
          min: 15.0
          max: 30

    pursuers:
      # observation 
      is_controlled: false
      state_limits:
        x:
          min: -inf
          max: inf
        y:
          min: -inf
          max: inf
        z:
          min: 30.0
          max: 100.0
        phi:
          min: !!float -0.7853981633974483   # -np.deg2rad(45)
          max: !!float 0.7853981633974483    # np.deg2rad(45)
        theta:
          min: !!float -0.4363323129985824   # -np.deg2rad(25)
          max: !!float 0.3490658503988659    # np.deg2rad(20)
        psi:
          min: !!float -3.14159    # -np.deg2rad(180)
          max: !!float 3.14159     # np.deg2rad(180)
        v:
          min: 12.0
          max: 35.0
        vx:
          min: -35.0
          max: 35.0
        vy:
          min: -35.0
          max: 35.0
        vz:
          min: -35.0
          max: 35.0

      control_limits:
        u_phi:
          min: !!float -0.7853981633974483   # -np.deg2rad(45)
          max: !!float 0.7853981633974483    # np.deg2rad(45)
        u_theta:
          min: !!float -0.4363323129985824   # -np.deg2rad(25)
          max: !!float 0.3490658503988659    # np.deg2rad(20)
        u_psi:
          min: !!float -3.14159 #radians
          max: !!float 3.14159  #radians
        v_cmd:
          min: 15.0
          max: 30



